[package]
name = "rusty_sky"
version = "0.1.0"
authors = ["Cameron Shannon <cameroncshannon@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde_json = "1.0.39"
serde_derive = "1.0.91"
serde = "1.0.91"
url = "1.7.2"